server:
  port: 8080

# H2 Database
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:dcbapp
    username: ${DB_USERNAME}
    password: password

# Dataset
dataset:
  pets:
    - name: Mogli
      birthDate: 2021-01-01
      petType: CAT
      sexType: MALE
    - name: Bob
      birthDate: 2020-02-10
      petType: DOG
      sexType: MALE
    - name: Lala
      birthDate: 2019-02-10
      petType: DOG
      sexType: FEMALE
  reminders:
    - date: 2022-10-28
      time: "09:15:00"
      title: Take Mogli to meet a sitter
      description: Remember to bring its goodies
      active: true
    - date: 2022-10-29
      time: "10:20:00"
      title: Vaccinate Mogli and Bob
      description: Remember bring vaccination card
      active: true
    - date: 2022-10-30
      time: "13:30:00"
      title: Take Bob to meet its dog sitter
      description: Check if he behaves
      active: true
    - date: 2022-11-04
      time: "08:30:00"
      title: Take Bob to the Vet
      description: Need to ask for dewormer
      active: true