server:
  port: 8080

# Postgres Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/pejo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

# Mail sender API
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Dataset
dataset:
  pets:
    - name: Mogli
      birthDate: 2021-01-01
      petType: CAT
      sexType: MALE
    - name: Bob
      birthDate: 2020-02-10
      petType: DOG
      sexType: MALE
    - name: Lala
      birthDate: 2019-02-10
      petType: DOG
      sexType: FEMALE
  reminders:
    - date: 2022-11-17
      time: "09:15:00"
      title: Take Mogli to meet a sitter
      description: Remember to bring its goodies
      active: true
    - date: 2022-11-20
      time: "10:20:00"
      title: Vaccinate Mogli and Bob
      description: Remember bring vaccination card
      active: true
    - date: 2022-11-30
      time: "13:30:00"
      title: Take Bob to meet its dog sitter
      description: Check if he behaves
      active: true
    - date: 2022-11-04
      time: "08:30:00"
      title: Take Bob to the Vet
      description: Need to ask for dewormer
      active: true

# Certifications
rsa:
  private-key: classpath:certifications/private.pem
  public-key: classpath:certifications/public.pem
