server:
  port: 8080

# H2 Database
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:dcbapp
    username: sa
    password: password

# Dataset
dataset:
  pets:
    - name: Mogli
      birthDate: 2021-01-01
      petType: CAT
      sexType: MALE
    - name: Bob
      birthDate: 2020-02-10
      petType: DOG
      sexType: MALE
    - name: Lala
      birthDate: 2019-02-10
      petType: DOG
      sexType: FEMALE
  reminders:
    - date: 2022-10-28
      time: "09:15:00"
      title: Take mogli to the Vet
      description: Remember to bring its blood test
      active: true
    - date: 2022-10-29
      time: "10:20:00"
      title: Vaccinate mogli and bob
      description: Remember bring vaccination card
      active: true
    - date: 2022-10-30
      time: "13:30:00"
      title: Take bob to meet the setter
      description: Test description 3
      active: true
    - date: 2022-11-04
      time: "08:30:00"
      title: Take bob to the vet
      description: Need to ask for dewormer
      active: true